"""create stocks

Revision ID: bb19f3ddd6d4
Revises: 
Create Date: 2023-12-26 14:34:08.767042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb19f3ddd6d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('symbol', sa.String(length=255)),
        sa.Column('current_price', sa.Float)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
